author: MDCollins
database: false
description: Additional control for Grief Prevention
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.gp_controls.GP_Controls
name: GP_Controls
startup: postworld
url: http://blockmovers.com/
version: '0.1'
depend: [GriefPrevention]
commands:
  wild:
    usage: /<command>
    aliases: wilderness
  toggle:
    usage: /<command>
permissions:
  gp_c.admin:
    default: false
    children:
      gp_c.exempt.all: true
      gp_c.modify.buildlist: true
      gp_c.modify.destroylist: true
      gp_c.toggle.pvp.any: true
      gp_c.toggle.mobs.any: true
  gp_c.exempt.all:
    default: false
    children:
      gp_c.exempt.build: true
      gp_c.exempt.destroy: true
  gp_c.exempt.build:
    default: false
  gp_c.exempt.destroy:
    default: false
  gp_c.modify.buildlist:
    default: false
  gp_c.modify.destroylist:
    default: false
  gp_c.toggle.pvp.any:
    default: false
  gp_c.toggle.pvp.self:
    default false:
  gp_c.toggle.mobs.any:
    default: false
  gp_c.toggle.mobs.self:
    default: false