author: MDCollins
database: false
description: Wilderness control for Grief Prevention
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.gp_wildernesscontrol.GP_WildernessControl
name: GP_WildernessControl
startup: postworld
url: http://blockmovers.com/
version: '0.1'
